field_perms = {     'teacher':{
                        'info':[
                            'teacher',
                            'regular_User',
                            'observer',
                            'mentor',
                            'admin',
                        ]
                    },
                    'regular':{
                        'grad_date':[
                            'teacher',
                            'admin',
                        ],
                        'birthdate':[
                            'teacher',
                            'mentor',
                            'admin',
                        ],
                        'birthplace':[
                            'admin',                        
                        ],
                        'postal_code':[
                            'admin',
                        ],
                        'country':[
                            'teacher',
                            'mentor',
                            'admin',
                        ],
                        'city':[
                            'teacher',
                            'admin',
                        ],
                        'street':[
                            'admin',
                        ],
                        'building':[
                            'admin',
                        ],
                        'housing':[
                            'admin',
                        ],
                        'appartment':[
                            'admin',
                        ],
                        'parent_1':[
                            'mentor',
                            'admin',
                        ],
                        'parent_1_phone':[
                            'mentor',
                            'admin',
                        ],
                        'parent_2':[
                            'mentor',
                            'admin',                            
                        ],
                        'parent_2_phone':[
                            'mentor',
                            'admin',
                        ],
                        'school':[
                            'teacher',
                            'mentor',
                            'admin',
                        ],
                    },
                    'observer':{
                    },
                    'mentor':{
                    },
                    'admin':{
                    },
                    'event_worker':{
                    },
    }
