field_perms = {     'Teacher':{
                        'info':[
                            'Teacher',
                            'RegularUser',
                            'Observer',
                            'Mentor',
                            'Admin',
                        ]
                    },
                    'RegularUser':{
                        'grad_date':[
                            'Teacher',
                            'Admin',
                        ],
                        'birthdate':[
                            'Teacher',
                            'Mentor',
                            'Admin',
                        ],
                        'birthplace':[
                            'Admin',                        
                        ],
                        'postal_code':[
                            'Admin',
                        ],
                        'country':[
                            'Teacher',
                            'Mentor',
                            'Admin',
                        ],
                        'city':[
                            'Teacher',
                            'Admin',
                        ],
                        'street':[
                            'Admin',
                        ],
                        'building':[
                            'Admin',
                        ],
                        'housing':[
                            'Admin',
                        ],
                        'appartment':[
                            'Admin',
                        ],
                        'parent_1':[
                            'Mentor',
                            'Admin',
                        ],
                        'parent_1_phone':[
                            'Mentor',
                            'Admin',
                        ],
                        'parent_2':[
                            'Mentor',
                            'Admin',                            
                        ],
                        'parent_2_phone':[
                            'Mentor',
                            'Admin',
                        ],
                        'school':[
                            'Teacher',
                            'Mentor',
                            'Admin',
                        ],
                    },
                    'Observer':{
                    },
                    'Mentor':{
                    },
                    'Admin':{
                    }
    }
